apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authentication
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"        
        autoscaling.knative.dev/maxScale: "10"      
        autoscaling.knative.dev/target: "50"        
    spec:
      containers:
        - image: mascorpion/ds:latest
          command: ["authentication/authentication"]
          ports:
            - containerPort: 50051   
              name: h2c                 
          env:
            - name: ENV_VAR
              value: "value2"                    
          resources:
            requests:
              cpu: "100m"                       
              memory: "128Mi"

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authorization
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"        
        autoscaling.knative.dev/maxScale: "10"      
        autoscaling.knative.dev/target: "50"        
    spec:
      containers:
        - image: mascorpion/ds:latest
          command: ["authorization/authorization"]
          ports:
            - containerPort: 50051     
              name: h2c              
          env:
            - name: ENV_VAR
              value: "value2"                    
          resources:
            requests:
              cpu: "100m"                       
              memory: "128Mi"             


---


apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: scheduler
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"        
        autoscaling.knative.dev/maxScale: "1"      
        autoscaling.knative.dev/target: "500"        
    spec:
      containers:
        - image: mascorpion/ds:latest
          command: ["scheduler/scheduler"]
          ports:
            - containerPort: 50051  
              name: h2c                  
          env:
            - name: ENV_VAR
              value: "value2"                    
          resources:
            requests:
              cpu: "100m"                       
              memory: "128Mi"             

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: write-to-etcd
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"        
        autoscaling.knative.dev/maxScale: "10"      
        autoscaling.knative.dev/target: "50"        
    spec:
      containers:
        - image: mascorpion/ds:latest
          command: ["writeToEtcd/writeToEtcd"]
          ports:
            - containerPort: 50051  
              name: h2c                  
          env:
            - name: ENV_VAR
              value: "value2"                    
          resources:
            requests:
              cpu: "100m"                       
              memory: "128Mi"             

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: metric-collector
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"        
        autoscaling.knative.dev/maxScale: "10"      
        autoscaling.knative.dev/target: "20"        
    spec:
      containers:
        - image: mascorpion/ds:latest
          command: ["metricCollector/metricCollector"]
          ports:
            - containerPort: 50051    
              name: h2c                
          env:
            - name: ENV_VAR
              value: "value2"                    
          resources:
            requests:
              cpu: "100m"                       
              memory: "128Mi"             

---




apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: node-checker
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/target: "20"
    spec:
      containers:
        - image: mascorpion/ds:latest
          command: ["nodeChecker/nodeChecker"]
          ports:
            - containerPort: 50051
              name: h2c
          env:
            - name: ENV_VAR
              value: "value6"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"


---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: horizontal-pod-autoscaler
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/target: "20"
    spec:
      containers:
        - image: mascorpion/ds:latest
          command: ["horizontalpodautoscaler/horizontalpodautoscaler"]
          ports:
            - containerPort: 50051
              name: h2c
          env:
            - name: ENV_VAR
              value: "value6"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"